// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef dance_h
#define dance_h
#include <FL/Fl.H>
#include <FL/Fl_JPEG_Image.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_GIF_Image.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>

class Game_Window : public Fl_Double_Window {
  void _Game_Window();
public:
  Game_Window(int X, int Y, int W, int H, const char *L = 0);
  Game_Window(int W, int H, const char *L = 0);
private:
  int handle(int e); 
public:
  Fl_Box *box_background;
  Fl_Box *box_key;
  Fl_Box *carlton;
  Fl_Box *justin;
  Fl_Box *mj;
  Fl_Box *snoop;
};
Game_Window* make_window();
#endif
