// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "dance.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(240, 210);
    w = o;
    o->end();
  } // Fl_Double_Window* o
  return w;
}
