// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "dance.h"
#include <FL/Fl_Double_Window.H>
Game_Window::Game_Window(int X, int Y, int W, int H, const char *L)
  : Fl_Double_Window(X, Y, W, H, L) {
  _Game_Window();
}

Game_Window::Game_Window(int W, int H, const char *L)
  : Fl_Double_Window(0, 0, W, H, L) {
  clear_flag(16);
  _Game_Window();
}

Game_Window::Game_Window()
  : Fl_Double_Window(0, 0, 500, 500, "Dance Game") {
  clear_flag(16);
  _Game_Window();
}

void Game_Window::_Game_Window() {
this->box(FL_FLAT_BOX);
this->color(FL_GRAY0);
this->selection_color(FL_BACKGROUND_COLOR);
this->labeltype(FL_NO_LABEL);
this->labelfont(0);
this->labelsize(14);
this->labelcolor(FL_FOREGROUND_COLOR);
this->align(Fl_Align(FL_ALIGN_TOP));
this->when(FL_WHEN_RELEASE);
{ box_background = new Fl_Box(0, 0, 500, 400);
  box_background->color((Fl_Color)48);
} // Fl_Box* box_background
{ box_key = new Fl_Box(210, 410, 80, 80);
} // Fl_Box* box_key
end();
}

Game_Window* make_window() {
  return new Game_Window(500,500,"Dancing Game");
}
