// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef dance_h
#define dance_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_JPEG_Image.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_GIF_Image.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
extern Fl_Box *box_background;
extern Fl_Box *box_key;
Fl_Double_Window* make_window();
#endif
